// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACOrP4YkWImkoTn_DLtxR1qF1fMO5lQVo',
    appId: '1:797028995614:android:6fc27d5db3aadd5680940f',
    messagingSenderId: '797028995614',
    projectId: 'resqteam-c04df',
    databaseURL: 'https://resqteam-c04df-default-rtdb.firebaseio.com',
    storageBucket: 'resqteam-c04df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaMRgyZ8rYJzhRuro6ZAPQjmEPSYmOhdc',
    appId: '1:797028995614:ios:5480d6490c971d1480940f',
    messagingSenderId: '797028995614',
    projectId: 'resqteam-c04df',
    databaseURL: 'https://resqteam-c04df-default-rtdb.firebaseio.com',
    storageBucket: 'resqteam-c04df.appspot.com',
    androidClientId: '797028995614-dalr3b856in444n3kkmcu107p5othssj.apps.googleusercontent.com',
    iosClientId: '797028995614-hl1guj48q8rqts9r02m73fnib569j55j.apps.googleusercontent.com',
    iosBundleId: 'com.example.redqteam',
  );
}
